- gpustack/server/system_load.py
https://github.com/gpustack/gpustack/issues/93
> fix: mismatching return

- README.md
- docs/user-guide/openai-compatible-apis.md
- gpustack/api/middlewares.py
- gpustack/routes/dashboard.py
- gpustack/routes/openai.py
- gpustack/schemas/model_usage.py
- gpustack/worker/inference_server.py
- hack/install.sh
- hack/windows/install.ps1
https://github.com/gpustack/gpustack/issues/95
> feat: more openai apis

- gpustack/third_party/config/fastfetch/config.jsonc
- gpustack/worker/collector.py
- hack/install.sh
- hack/windows/build.ps1
- hack/windows/install.ps1
https://github.com/gpustack/gpustack/issues/111
https://github.com/gpustack/gpustack/issues/114
> Enhance collector and fix bugs

- docs/upgrade.md
> chore: add doc for upgrade windows

- .github/workflows/ci.yml
- Dockerfile
- docker-compose.yaml
- docs/installation/docker-installation.md
- mkdocs.yml
> feat: support docker image and docker-compose

- README.md
- docs/overview.md
- gpustack/schemas/workers.py
- install.sh
- install.sh.sha256sum
Since [pull request #8383](https://github.com/ggerganov/llama.cpp/pull/8383) has been merged into [llama.cpp](https://github.com/ggerganov/llama.cpp), I would like to add MTGPU support to GPUStack. This PR might be the first step towards that goal.
> feat: Support Moore Threads GPU

- docker-compose.yaml
> refactor: add volume to docker compose

- .github/workflows/ci.yml
- Dockerfile
- gpustack/worker/downloaders.py
- hack/install.sh
- hack/windows/install.ps1
- poetry.lock
- pyproject.toml
> fix: can't download llama 3.1 and other bugs

- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/159
> fix: use platform to collect system info

- docs/quickstart.md
Change G to C in the title
`Guickstart` -> `Quickstart`
> fix: update quickstart title

- gpustack/routes/openai.py
https://github.com/gpustack/gpustack/issues/129
> fix: missing stream content-type

- gpustack/routes/dashboard.py
- gpustack/scheduler/policy.py
- gpustack/schemas/stmt.py
- gpustack/schemas/workers.py
- gpustack/server/system_load.py
https://github.com/gpustack/gpustack/issues/172
> fix: iterating none gpu_devices

- install.sh
- install.sh.sha256sum
> fix: add dependency check while selinux is enable

- docs/cli-reference/start.md
- docs/user-guide/model-management.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/scheduler/calculator.py
- gpustack/scheduler/scheduler.py
- gpustack/server/server.py
- gpustack/utils/validators.py
- gpustack/worker/downloaders.py
- gpustack/worker/inference_server.py
- gpustack/worker/serve_manager.py
- hack/install.sh
- hack/windows/install.ps1
- poetry.lock
- pyproject.toml
Add support for https://github.com/gpustack/gpustack/issues/182
And address https://github.com/gpustack/gpustack/issues/180 by updating box
> feat: custom ollama library

- gpustack/cmd/start.py
https://github.com/gpustack/gpustack/issues/192
> fix: optional bool for start cmd

- docs/overview.md
- hack/install.sh
- hack/windows/install.ps1
https://github.com/gpustack/gpustack/issues/216
> feat: extend nvidia gpu compute capability support

- gpustack/policies/calculator.py
- gpustack/policies/resource_fit_policy.py
- gpustack/server/controllers.py
- gpustack/worker/inference_server.py
https://github.com/gpustack/gpustack/issues/219
https://github.com/gpustack/gpustack/issues/215
https://github.com/gpustack/gpustack/issues/223
> refactor: diable mmap for schedule and deploy model instance and fix scale down bug

- gpustack/policies/calculator.py
- gpustack/utils/hugging_face.py
- gpustack/worker/downloaders.py
- gpustack/worker/inference_server.py
https://github.com/gpustack/gpustack/issues/190
Example usage:
```
curl -X POST X/v1/models \
-H "Content-Type: application/json" \
-d '{
"source": "huggingface",
"huggingface_repo_id": "foo/bar",
"huggingface_filename": "qwen2-0_5b-instruct-q4_k_m*",
...
}'
```
> feat: support sharded GGUF model files

- gpustack/policies/resource_fit_policy.py
- gpustack/schemas/models.py
https://github.com/gpustack/gpustack/issues/231
> fix: partial offload error

- docs/cli-reference/start.md
- docs/installation/installation-script.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/migrations/versions/2024_09_09_1625-599e39158abe_update_memory_and_gpu_memory_to_ram_and_.py
- gpustack/policies/resource_fit_policy.py
- gpustack/routes/dashboard.py
- gpustack/schemas/dashboard.py
- gpustack/schemas/system_load.py
- gpustack/schemas/workers.py
- gpustack/server/system_load.py
- gpustack/worker/worker.py
- tests/fixtures/workers/fixtures.py
> fix dashboard allocated is empty and rename memory and gpu memory to ram and vram

- gpustack/policies/resource_fit_policy.py
> fix: negative allocatable will cause parser return empty vram data

- gpustack/routes/dashboard.py
Problem:
```
SAWarning: SELECT statement has a cartesian product between FROM element(s) "model_instances" and FROM element "anon_3".  Apply join condition(s) between each element to resolve.
```
Solution:
1. Use [joins_implicitly](https://docs.sqlalchemy.org/en/14/core/functions.html#sqlalchemy.sql.functions.FunctionElement.table_valued.params.joins_implicitly)
2. combine ram/vram subquery to reduce complexity
> refactor: use joins_implicitly querying active models

- gpustack/worker/downloaders.py
- gpustack/worker/logs.py
https://github.com/gpustack/gpustack/issues/230
https://github.com/gpustack/gpustack/issues/236
> fix: download non-library ollama model

- gpustack/policies/calculator.py
- gpustack/policies/resource_fit_policy.py
- gpustack/worker/inference_server.py
- hack/install.sh
- hack/windows/install.ps1
- tests/fixtures/estimates/fixtures.py
- tests/fixtures/estimates/llama3_70b_disable_offload_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_full_offload_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_2_4080_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_2_4090_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_2_4090_estimate_claim_2.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_2_4090_estimate_claim_3.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_3_4080_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_3_4080_estimate_claim_2.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_3_4080_estimate_claim_3.json
- tests/fixtures/estimates/llama3_70b_full_offload_split_4_4080_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_partial_offload_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_partial_offload_split_2_4080_4090_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_partial_offload_split_2_4080_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_partial_offload_split_3_4080_4090_estimate_claim.json
- tests/fixtures/estimates/llama3_70b_partial_offload_split_3_4080_4090_estimate_claim_2.json
- tests/fixtures/estimates/llama3_8b_disable_offload_estimate_claim.json
- tests/fixtures/estimates/llama3_8b_full_offload_estimate_claim.json
- tests/fixtures/estimates/llama3_8b_partial_offload_estimate_claim.json
- tests/scheduler/test_scheduler.py
> refactor: update main worker and rpc server sequence to consist with parser and llama-box

- gpustack/worker/inference_server.py
> fix: missing tensor split when main gpu index len is 1

- gpustack/utils/process.py
- gpustack/worker/inference_server.py
- gpustack/worker/rpc_server.py
- gpustack/worker/serve_manager.py
- gpustack/worker/worker.py
- gpustack/worker/worker_manager.py
> fix: can't start llama-box in windows

- gpustack/worker/serve_manager.py
https://github.com/gpustack/gpustack/issues/268
Problem:
When a worker disconnect then reconnect, the instance is in Scheduled state.
> fix: restart serving process for rescheduled instance

- hack/install.sh
- hack/windows/install.ps1
https://github.com/gpustack/gpustack/issues/283
> chore: bump llama-box

- Dockerfile
- gpustack/scheduler/scheduler.py
- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/284
> fix: add tzdata

- gpustack/routes/proxy.py
- gpustack/routes/routes.py
> feat: support server-side proxy

- gpustack/server/app.py
- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/306
> feat: auto select faster cdn for api docs

- install.sh
- install.sh.sha256sum
https://github.com/gpustack/gpustack/issues/211
> fix: avoid cuda_check false alarm

- docs/cli-reference/start.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/scheduler/calculator.py
- gpustack/worker/backends/base.py
- gpustack/worker/downloaders.py
> feat: support deploy huggingface model require token

- gpustack/scheduler/calculator.py
- gpustack/worker/collector.py
- hack/install.sh
- hack/windows/install.ps1
> Upgrade fastfetch and support windows arm

- poetry.lock
- pyproject.toml
Add dependencies required for https://huggingface.co/mistralai/Pixtral-12B-2409
> fix: dependencies for pixtral inference

- gpustack/cmd/start.py
- gpustack/config/config.py
> fix: hf_token cmd flag isn't taking effect

- docs/overview.md
https://github.com/gpustack/gpustack/issues/288
> docs: update the supported platforms

- hack/install.sh
- hack/windows/install.ps1
Possibly address https://github.com/gpustack/gpustack/issues/290
> chore: bump box

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
> fix: hf api hang when hf isn't reachable

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/worker/backends/base.py
- gpustack/worker/backends/vllm.py
Mainly address https://github.com/gpustack/gpustack/issues/313
Also avoid downloading unneccessary weight files related to https://github.com/gpustack/gpustack/issues/319
> fix: set default max-model-len

- gpustack/scheduler/calculator.py
> fix: hf api hang when deploy with backend llama-box

- gpustack/worker/backends/base.py
- gpustack/worker/downloaders.py
Problem:
Previously, we compute download progress incremently when new downloads start. It makes the progress flaky, especially when the file number exceeds the concurrency.
Solution:
Compute total file size before downloading.
Should address the following issues:
https://github.com/gpustack/gpustack/issues/312
https://github.com/gpustack/gpustack/issues/337
https://github.com/gpustack/gpustack/issues/254
> refactor: get total model size before download

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/worker/backends/base.py
- gpustack/worker/backends/vllm.py
- gpustack/worker/downloaders.py
Address https://github.com/gpustack/gpustack/issues/340
Currently, users can not disable this flag. It would make more sense and be safer to set it on demand.
> chore: change default trust_remote_code

- gpustack/worker/backends/llama_box.py
> fix: llama-box customize parameter do not take effect

- gpustack/worker/backends/llama_box.py
> fix: llama-box customize parameter without value do not take effect

- gpustack/chat/manager.py
https://github.com/gpustack/gpustack/issues/352
> fix: model default values for cli chat

- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/361
Problem:
In modelscope file_download [implementation](https://github.com/modelscope/modelscope/blob/b0f03ffd6d7d82133d47027291b23aae6d576d55/modelscope/hub/utils/caching.py#L268), it compares revision for each file but it only stores one revision in repo metadata. So redownload happens when multiple files are from different git revisions.
Solution:
use snapshot_download.
> fix: use snapshot_download for multiple modelscope files

- gpustack/schemas/workers.py
> fix: update vendor name of Moore Threads

- gpustack/scheduler/calculator.py
- gpustack/utils/command.py
- gpustack/utils/platform.py
- gpustack/worker/backends/llama_box.py
- gpustack/worker/collector.py
- gpustack/worker/rpc_server.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
- hack/install.sh
- hack/windows/install.ps1
- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/304
> refactor: do not package prebuilt binaries

- gpustack/worker/backends/vllm.py
- tests/pretrained_config/test_pretrained_config.py
https://github.com/gpustack/gpustack/issues/345
> fix: init scaling factor

- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/393
There's no lock mechanism to prevent parallel downloading in modelscope library. Implement on our side.
> fix: file lock for modelscope downloading

- Dockerfile
- hack/build-docker.sh
> chore: purge pip cache in image

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/397
> feat: add retry on tools download

- docs/user-guide/inference-backends.md
- gpustack/utils/platform.py
- poetry.lock
- pyproject.toml
> feat: support deploy model in windows arm

- docs/cli-reference/start.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/utils/platform.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/304
> improve device detect and make tools download url configurable

- gpustack/server/update_check.py
> chore: ignore device

- gpustack/config/config.py
- gpustack/detectors/custom/custom.py
- gpustack/detectors/detector_factory.py
- gpustack/schemas/workers.py
- gpustack/server/system_load.py
- gpustack/utils/platform.py
- gpustack/worker/backends/base.py
- gpustack/worker/collector.py
- gpustack/worker/exporter.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
- gpustack/worker/worker_manager.py
> feat: support user-defined gpus

- gpustack/api/exceptions.py
- gpustack/api/responses.py
- gpustack/detectors/fastfetch/fastfetch.py
- gpustack/detectors/npu_smi/npu_smi.py
- gpustack/routes/openai.py
- gpustack/routes/routes.py
- gpustack/scheduler/calculator.py
Related to https://github.com/gpustack/gpustack/issues/401
1. Handle exceptions in streaming.
2. Response openai format error in /v1-openai APIs.
> refactor: openai api exceptions

- gpustack/api/middlewares.py
yield chunk regardless of streaming exception. potentially mitigate https://github.com/gpustack/gpustack/issues/376
> refactor: yield chunk on streaming exception

- gpustack/worker/backends/llama_box.py
> fix: set process priority

- gpustack/scheduler/scheduler.py
Potentially mitigate https://github.com/gpustack/gpustack/issues/445
> fix: model instance state

- gpustack/api/responses.py
https://github.com/gpustack/gpustack/issues/315
> fix: empty error body

- gpustack/worker/worker.py
> fix: delay start rpc server

- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/452
> fix: handle none architectures

- gpustack/worker/backends/base.py
- gpustack/worker/rpc_server.py
- gpustack/worker/worker_manager.py
> refactor: limit rpc server device

- gpustack/worker/worker.py
> fix: model instance endpoint update failed

- gpustack/worker/tools_manager.py
> fix: tools not upgraded after upgrading gpustack

- hack/build.sh
Issues resolved, tidy up again
> ci: tidy up packages

- pyproject.toml
https://github.com/gpustack/gpustack/issues/505
> chore: update extra dependencies

- docs/cli-reference/start.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/scheduler/scheduler.py
- gpustack/worker/backends/base.py
- gpustack/worker/serve_manager.py
https://github.com/gpustack/gpustack/issues/504
> feat: support configuring cache-dir

- docs/architecture.md
- docs/cli-reference/start.md
- docs/installation/installation-script.md
- gpustack/api/middlewares.py
- gpustack/cmd/start.py
- gpustack/migrations/versions/2024_07_24_1113-1dd9fa5b38ff_initialize_tables.py
- gpustack/migrations/versions/2024_09_11_1629-6dcb3a50da19_update_model_instance_and_system_load_for_.py
- gpustack/mixins/active_record.py
- gpustack/routes/dashboard.py
- gpustack/schemas/stmt.py
- gpustack/schemas/workers.py
- gpustack/server/db.py
- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/85
> feat: support postgresql

- gpustack/routes/dashboard.py
https://github.com/gpustack/gpustack/issues/85#issuecomment-2461447168
> fix: cast big int

- docs/troubleshooting.md
- gpustack/cmd/reset_admin_password.py
- gpustack/main.py
- gpustack/server/auth.py
Make the reset password UX simpler
> feat: add reset pswd command

- .github/workflows/ci.yml
- .github/workflows/docker-ci.yaml
- Dockerfile
- Dockerfile.npu
- docker-compose.yaml
- gpustack/detectors/fastfetch/fastfetch.py
- hack/build.sh
1. Build py3-none-any wheel
2. Ship docker image per device
> refactor: update docker ci

- Dockerfile
- Dockerfile.npu
- gpustack/cmd/download_tools.py
- gpustack/main.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/525
> refactor: package tools in docker images

- gpustack/routes/proxy.py
https://github.com/gpustack/gpustack/issues/543
> chore: set proxy timeout

- gpustack/scheduler/calculator.py
https://github.com/gpustack/gpustack/issues/532
> feat: Parameter-aware estimation for GGUF

- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/491
> fix: lack of state message

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/scheduler/calculator.py
- gpustack/worker/backends/llama_box.py
https://github.com/gpustack/gpustack/issues/494
> feat: respect tensor-split param in gguf scheduling

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/522
> fix: estimate local model weight

- docs/cli-reference/download-tools.md
- docs/installation/air-gapped-installation.md
- gpustack/cmd/download_tools.py
- gpustack/main.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
- mkdocs.yml
https://github.com/gpustack/gpustack/issues/408
> feat: airgap instruction

- docs/installation/air-gapped-installation.md
- gpustack/cmd/download_tools.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/408
> refactor: remove cache before download-tools

- gpustack/schemas/models.py
https://github.com/gpustack/gpustack/issues/548
https://github.com/gpustack/gpustack/issues/563
> fix: is gguf by backend

- docs/user-guide/model-management.md
- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/scheduler/calculator.py
- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/571
> refactor: skip resource estimation for local path model if not possible

- pyproject.toml
https://github.com/gpustack/gpustack/issues/581
> chore: update dependency

- gpustack/cmd/start.py
- gpustack/routes/proxy.py
https://github.com/gpustack/gpustack/issues/419
> fix: clear referer in proxy

- pyproject.toml
https://github.com/gpustack/gpustack/issues/589
> fix: update dependency

- gpustack/config/config.py
- gpustack/server/server.py
https://github.com/gpustack/gpustack/issues/594
> chore: add newline to the generated password file

- docs/installation/installation-script.md
- gpustack/routes/proxy.py
https://github.com/gpustack/gpustack/issues/419
> fix: handle query and response headers in proxy

- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/logging.py
- gpustack/migrations/versions/2024_11_04_1347-004c73a5c09e_add_local_path.py
- gpustack/schemas/models.py
- gpustack/utils/command.py
- gpustack/worker/backends/base.py
- gpustack/worker/backends/llama_box.py
- gpustack/worker/backends/vllm.py
- gpustack/worker/serve_manager.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/197
> feat: add backend version

- gpustack/detectors/detector_factory.py
- gpustack/detectors/fastfetch/fastfetch.py
- gpustack/detectors/nvidia_smi/nvidia_smi.py
- gpustack/worker/collector.py
- gpustack/worker/worker_manager.py
> refactor: replace detect_gpus_by_vendor with detect_gpus_by_device and update nvidia gpus detector

- gpustack/routes/proxy.py
> fix: remove query merging

- gpustack/detectors/detector_factory.py
- hack/install.sh
> refactor: skip gpu detection while no gpu device

- gpustack/policies/candidate_selectors/vox_box_resource_fit_selector.py
> fix: skip non-nvidia gpus while auto schedule

- gpustack/routes/proxy.py
https://github.com/gpustack/gpustack/issues/419
> fix: use identity content encoding in proxy

- gpustack/worker/backends/vox_box.py
> fix: remove cuda visible env while running vox-box

- gpustack/api/middlewares.py
- gpustack/schemas/images.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/426
> fix: support image streaming

- gpustack/api/middlewares.py
- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/routes/openai.py
- gpustack/scheduler/calculator.py
- gpustack/schemas/images.py
- gpustack/utils/command.py
https://github.com/gpustack/gpustack/issues/623
> fix: broken image chunk

- gpustack/routes/models.py
- gpustack/routes/openai.py
- gpustack/routes/routes.py
- gpustack/routes/voice.py
- poetry.lock
- pyproject.toml
> refactor: update voice api

- gpustack/policies/candidate_selectors/vox_box_resource_fit_selector.py
- gpustack/scheduler/scheduler.py
- gpustack/utils/file.py
- gpustack/worker/backends/base.py
- gpustack/worker/downloaders.py
- poetry.lock
- pyproject.toml
> feat: support resource estimate for audio model

- gpustack/api/responses.py
- gpustack/routes/openai.py
https://github.com/gpustack/gpustack/issues/631
> fix: response error in stream

- gpustack/cli/draw.py
https://github.com/gpustack/gpustack/issues/656
> fix: handle draw output

- gpustack/policies/candidate_selectors/vox_box_resource_fit_selector.py
- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/667
> fix: async estimate vox

- gpustack/cmd/chat.py
- gpustack/cmd/download_tools.py
- gpustack/cmd/draw.py
- gpustack/cmd/start.py
- gpustack/main.py
- gpustack/server/server.py
- gpustack/utils/signal.py
- gpustack/utils/task.py
- gpustack/worker/rpc_server.py
- gpustack/worker/serve_manager.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/204
https://github.com/gpustack/gpustack/issues/154
> fix: graceful exit

- gpustack/worker/worker.py
> fix: model instance serving ip not updated

- Dockerfile
> chore: update base image for cuda

- gpustack/cmd/start.py
https://github.com/gpustack/gpustack/issues/690
> fix: spawn multiprocessing

- gpustack/scheduler/calculator.py
https://github.com/gpustack/gpustack/issues/694
> fix: full offloading for empty estimation

- poetry.lock
- pyproject.toml
> chore: upgrade vox-box from 0.0.6 to 0.0.7

- gpustack/logging.py
- gpustack/worker/serve_manager.py
https://github.com/gpustack/gpustack/issues/682
https://github.com/gpustack/gpustack/issues/685
> refactor: redirect logs

- gpustack/scheduler/calculator.py
- gpustack/utils/hub.py
https://github.com/gpustack/gpustack/issues/702
> fix: hf subdirs

- gpustack/api/exceptions.py
- gpustack/routes/openai.py
> fix: extend proxy timeout

- docs/cli-reference/draw.md
- docs/quickstart.md
- gpustack/cli/base.py
- gpustack/cli/draw.py
- gpustack/cmd/draw.py
https://github.com/gpustack/gpustack/issues/720
> fix: no warmup for cli generated model

- docs/installation/air-gapped-installation.md
> fix: update pip download command

- gpustack/scheduler/calculator.py
https://github.com/gpustack/gpustack/issues/759
> fix: skip range download detect calling parser

- gpustack/scheduler/calculator.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/759
> chore: bump parser

- gpustack/api/middlewares.py
https://github.com/gpustack/gpustack/issues/680
> fix: transcription response class

- gpustack/detectors/fastfetch/fastfetch.py
- gpustack/detectors/npu_smi/npu_smi.py
- gpustack/detectors/nvidia_smi/nvidia_smi.py
- gpustack/worker/collector.py
> fix: empty result cause undefined variable

- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/770
> fix: mismatch function param

- gpustack/detectors/nvidia_smi/nvidia_smi.py
> fix: handle no device result from nvidia-smi

- docs/user-guide/inference-backends.md
- gpustack/schemas/models.py
- gpustack/utils/hub.py
- gpustack/worker/backends/base.py
- gpustack/worker/backends/llama_box.py
- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/819
> feat: support vlm in box

- gpustack/policies/candidate_selectors/vox_box_resource_fit_selector.py
- gpustack/worker/downloaders.py
> fix: scheduler failed to estimate audio model with local path

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- tests/policies/test_vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/645
> fix: update vllm model estimation

- gpustack/api/middlewares.py
https://github.com/gpustack/gpustack/issues/801
> fix: handle alias paths in middlewares

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- tests/scheduler/test_scheduler.py
https://github.com/gpustack/gpustack/issues/677
> chore: switch multi-worker and partial cpu priority

- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/743
> chore: pin builtin backend version

- gpustack/config/config.py
- gpustack/detectors/detector_factory.py
- gpustack/detectors/fastfetch/fastfetch.py
- gpustack/detectors/npu_smi/npu_smi.py
- gpustack/detectors/nvidia_smi/nvidia_smi.py
- gpustack/detectors/regredit/regredit.py
- gpustack/detectors/rocm_smi/rocm_smi.py
- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/policies/worker_filters/gpu_matching_filter.py
- gpustack/routes/models.py
- gpustack/schemas/models.py
- gpustack/schemas/stmt.py
- gpustack/schemas/workers.py
- gpustack/utils/gpu.py
- gpustack/utils/platform.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
- tests/detectors/npu_smi/test_npu_smi.py
- tests/utils/test_gpu.py
> feat: support select multiple gpus

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
> fix: skip gpu count calculation while user defined

- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
- gpustack/routes/openai.py
- gpustack/scheduler/scheduler.py
- gpustack/schemas/models.py
https://github.com/gpustack/gpustack/issues/810
https://github.com/gpustack/gpustack/issues/598
Deprecate previous category fields and add a unified categories field. 
It defaults to Auto in the UI and users can custom in advanced settings.
> feat: customizable model categories

- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/routes/openai.py
- gpustack/routes/voice.py
- gpustack/scheduler/scheduler.py
- gpustack/schemas/models.py
- gpustack/server/controllers.py
- gpustack/worker/backends/base.py
- gpustack/worker/backends/llama_box.py
- gpustack/worker/serve_manager.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/855
UI changes:
1. Adapt with model instances' `Starting` state.
2. query `/v1-openai/models?with_meta=true` to get meta infos.
> feat: support querying model metadata

- gpustack/routes/openai.py
> fix: skip transfer-encoding since the proxy will recalculate the content-length

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/utils/hub.py
> fix: add tensor parallel size check

- Dockerfile
- gpustack/cmd/download_tools.py
- gpustack/worker/tools_manager.py
> fix: container isn't installed pipx

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/798
> feat: choose fastest tools download base url

- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
- gpustack/routes/openai.py
- gpustack/scheduler/scheduler.py
- gpustack/schemas/models.py
https://github.com/gpustack/gpustack/issues/598
> feat: add 'llm' model category

- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/598
> fix: vllm models missing default category

- gpustack/detectors/npu_smi/npu_smi.py
- gpustack/detectors/nvidia_smi/nvidia_smi.py
- gpustack/detectors/rocm_smi/rocm_smi.py
- gpustack/utils/convert.py
> refactor: add safe convert

- gpustack/routes/proxy.py
> refactor: enhance proxy url validate

- gpustack/routes/openai.py
https://github.com/gpustack/gpustack/issues/744
> feat: support streaming form request

- gpustack/worker/downloaders.py
> fix: failed to download model with subpath from modelscope

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/645
> feat: recognize awq quant

- gpustack/routes/dashboard.py
- gpustack/schemas/dashboard.py
https://github.com/gpustack/gpustack/issues/727
> feat: add categories to active models

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
- gpustack/server/catalog.py
https://github.com/gpustack/gpustack/issues/738
> feat: catalog enhancements

- gpustack/api/middlewares.py
https://github.com/gpustack/gpustack/issues/852
> fix: exception on non-data SSE messages

- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/924
> fix: reranker marked as embedding

- tests/policies/test_vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/898
> ci: add retry

- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
- gpustack/schemas/workers.py
- gpustack/server/worker_syncer.py
- gpustack/utils/network.py
- gpustack/worker/collector.py
- gpustack/worker/exporter.py
- gpustack/worker/worker.py
- gpustack/worker/worker_manager.py
> feat: add worker unreachable check

- Dockerfile
- Dockerfile.cpu
- Dockerfile.musa
- Dockerfile.rocm
> fix: add pipx to support multiple vox-box versions

- gpustack/scheduler/scheduler.py
> fix: wrong function args number

- gpustack/server/catalog.py
- gpustack/worker/backends/base.py
https://github.com/gpustack/gpustack/issues/916
> fix: resolve data_dir variable in runtime

- gpustack/policies/worker_filters/gpu_matching_filter.py
- gpustack/routes/models.py
> fix: schedule issues

- gpustack/client/generated_model_client.py
- gpustack/client/generated_model_instance_client.py
- gpustack/client/generated_user_client.py
- gpustack/client/generated_worker_client.py
- gpustack/codegen/templates/client.py.jinja
- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
- gpustack/routes/workers.py
- gpustack/schemas/models.py
- gpustack/schemas/workers.py
- gpustack/server/controllers.py
- gpustack/server/worker_syncer.py
- gpustack/worker/worker_manager.py
> refactor: enhance connectivity detection

- poetry.lock
- pyproject.toml
> chore: upgrade vox-box from 0.0.10 to 0.0.11

- gpustack/worker/backends/llama_box.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/965
https://github.com/gpustack/gpustack/issues/878
> chore: update dependencies

- gpustack/scheduler/calculator.py
- gpustack/schemas/models.py
- gpustack/worker/backends/base.py
- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/971
> feat: mmproj-aware parser calling

- Dockerfile.npu
https://github.com/gpustack/gpustack/issues/755
> fix: Dockerfile cann version

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
- gpustack/schemas/models.py
- gpustack/worker/backends/llama_box.py
https://github.com/gpustack/gpustack/issues/963
> refactor: defaults to np1 for embedding & reranker models

- gpustack/routes/models.py
- gpustack/routes/openai.py
https://github.com/gpustack/gpustack/issues/922
> fix: category filtering in postgresql

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
https://github.com/gpustack/gpustack/issues/1008
> fix: update embedding & reranker model configurations in catalog

- gpustack/routes/dashboard.py
https://github.com/gpustack/gpustack/issues/922
> fix: active model query in pg

- gpustack/client/generated_http_client.py
- gpustack/client/generated_model_client.py
- gpustack/client/generated_model_instance_client.py
- gpustack/client/generated_user_client.py
- gpustack/client/generated_worker_client.py
- gpustack/codegen/templates/client.py.jinja
- gpustack/codegen/templates/http_client.py.jinja
- gpustack/worker/serve_manager.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/1006
> refactor: client async watch

- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
> fix: update migrate script to handle un_ready gpu devices

- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
> fix: migration script for pg lack of audio operation

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
Workaround for https://github.com/gpustack/gpustack/issues/1036
> fix: offload clip to cpu for sd3.5 medium fp16

- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/1048
> chore: update vLLM

- gpustack/routes/models.py
> fix: gpu selector validation

- install.sh
- install.sh.sha256sum
> refactor: handle ensurepip is disabled for system python

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1060
https://github.com/gpustack/gpustack/issues/1036
> feat: add deepseek r1

- gpustack/server/worker_syncer.py
> fix: add worker connectivity check to task

- gpustack/scheduler/scheduler.py
> fix: lock timezone for scheduler

- Dockerfile.rocm
- Dockerfile.rocm.base
- docs/tutorials/running-inference-with-amd-gpus.md
> chore: upgrade rocm vllm to v0.6.6.post1

- gpustack/routes/proxy.py
> fix: can't list private hf repos with token configured

- gpustack/worker/tools_manager.py
> fix: arm64 architecture uses the wrong llama-box binary

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/scheduler/calculator.py
- gpustack/schemas/models.py
- gpustack/worker/backends/llama_box.py
- tests/scheduler/test_scheduler.py
> fix: use the tensor-split generate from worker allocatable resources

- gpustack/routes/proxy.py
> fix: support list hf private repo

- gpustack/routes/proxy.py
- gpustack/scheduler/calculator.py
- gpustack/utils/hub.py
- gpustack/worker/downloaders.py
> fix: failed to deploy private hf repo

- docs/cli-reference/start.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/worker/worker.py
> fix: reserved 1GiB vram by default

- poetry.lock
- pyproject.toml
> chore: add bitsanbytes dependency

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
> refactor: enhance deepseek r1 catalog

- README.md
- README_CN.md
> task: update readme image link

- gpustack/scheduler/calculator.py
> refactor: support cache-type-k,cache-type-v backend params in calculator

- gpustack/config/config.py
- gpustack/utils/gpu.py
> fix: can't manual select dcu

- gpustack/assets/model-catalog-modelscope.yaml
> chore: get the ms vllm deepseek size 671 back

- gpustack/scheduler/calculator.py
- gpustack/worker/tools_manager.py
> refactor: support batch-size, ubatch-size, split-mode backend params

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
Related to https://github.com/gpustack/gpustack/issues/1131
> refactor: update r1 distill in catalog

- gpustack/scheduler/calculator.py
> refactor: add default calculator footprints

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1057
https://github.com/gpustack/gpustack/issues/1137
https://github.com/gpustack/gpustack/issues/1169
> chore: bump dependencies

- docs/assets/installation/air-gapped-installation/load_macos_dependencies.sh
- docs/assets/installation/air-gapped-installation/save_macos_dependencies.sh
- docs/installation/air-gapped-installation.md
> docs: update air gapped installation

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
> fix: the index function will raise an exception if the value is not present

- docs/troubleshooting.md
- gpustack/worker/serve_manager.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/1166
> feat: configurable worker log level

- docs/cli-reference/start.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/worker/rpc_server.py
- gpustack/worker/worker_manager.py
https://github.com/gpustack/gpustack/issues/1235
> feat: support configuring rpc-server arguments

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
- gpustack/schemas/models.py
- gpustack/worker/backends/base.py
- gpustack/worker/backends/llama_box.py
- gpustack/worker/backends/vllm.py
- gpustack/worker/backends/vox_box.py
https://github.com/gpustack/gpustack/issues/992
> feat: add model env

- gpustack/worker/serve_manager.py
https://github.com/gpustack/gpustack/issues/871
Problem:
watch_model_instances may halt before watch start if it fails to get current worker id
Solution:
Handle exception and retry properly
> fix: retry if get worker id fails

- gpustack/worker/serve_manager.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1230
> refactor: update health-check endpoint

- gpustack/config/config.py
- gpustack/detectors/base.py
- gpustack/detectors/custom/custom.py
- gpustack/detectors/detector_factory.py
- gpustack/detectors/fastfetch/fastfetch.py
- gpustack/schemas/workers.py
- gpustack/server/system_load.py
- gpustack/worker/collector.py
- gpustack/worker/exporter.py
- gpustack/worker/worker_manager.py
- Issue: #1258 
- Feature: support user-defined system info and fix bugs
- Issue: #1227 
- Problem: Should use the gpu index instead of the array index while update the allocated resource
- Issue: #1354
- Problem: Should set the allocated resource to 0 when no model instance existed
> feat: support user-defined system info and fix bugs

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- tests/policies/candidate_selectors/gguf/test_slow_gguf_resource_fit_selector.py
- Issue: #1121 
- Feature: Support scheduling with customized ngl. When user defined ngl, will check whether ngl is equal with full offload layers, call different candidate functions based on the ngl values. For partial offload(single cpu/worker, multiple worker), will set the offload layer to ngl to speed up the scheduling.
> feat: support scheduling with customized ngl

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- tests/policies/candidate_selectors/gguf/test_slow_gguf_resource_fit_selector.py
#1392
- fix: only select main and rpc could offload at least one layer to gpu
- refactor: refactor _generate_combinations_for_worker_with_rpcs, use _generate_combinations_for_worker_with_rpcs_with_selected_gpu_ids and _generate_combinations_for_worker_with_rpcs_without_selected_gpu_ids to make the logic simple
> fix: only select main and rpc could offload at least one layer to gpu

- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/1422
> chore: add python-json-logger

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/routes/models.py
> refactor: enhance ngl check

- docs/cli-reference/start.md
- docs/installation/docker-installation.md
- docs/installation/installation-requirements.md
- gpustack/api/auth.py
- gpustack/api/middlewares.py
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/ray/manager.py
- gpustack/routes/auth.py
- gpustack/routes/openai.py
- gpustack/routes/routes.py
- gpustack/routes/worker/logs.py
- gpustack/routes/worker/proxy.py
- gpustack/server/deps.py
- gpustack/utils/network.py
- gpustack/worker/serve_manager.py
- gpustack/worker/worker.py
- gpustack/worker/worker_manager.py
https://github.com/gpustack/gpustack/issues/921
https://github.com/gpustack/gpustack/issues/1406
1. Support custom port ranges
2. Add worker proxy with token auth so that service port exposure is not needed
3. Add Ray port configurations.
> refactor: sort out ports

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/routes/models.py
> refactor: enhance scheduling message

- gpustack/routes/openai.py
https://github.com/gpustack/gpustack/issues/1479
> fix: strip proxy auth header

- gpustack/cmd/start.py
- gpustack/utils/network.py
- gpustack/worker/serve_manager.py
- gpustack/worker/worker_manager.py
https://github.com/gpustack/gpustack/issues/1466
> fix: model instance port conflict

- gpustack/api/exceptions.py
- gpustack/client/generated_clientset.py
- gpustack/client/generated_model_client.py
- gpustack/client/generated_model_file_client.py
- gpustack/client/generated_model_instance_client.py
- gpustack/client/generated_worker_client.py
- gpustack/codegen/generate.py
- gpustack/codegen/templates/client.py.jinja
- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
- gpustack/policies/candidate_selectors/vox_box_resource_fit_selector.py
- gpustack/routes/model_files.py
- gpustack/routes/model_instances.py
- gpustack/routes/routes.py
- gpustack/schemas/__init__.py
- gpustack/schemas/links.py
- gpustack/schemas/model_files.py
- gpustack/schemas/models.py
- gpustack/server/controllers.py
- gpustack/server/server.py
- gpustack/utils/file.py
- gpustack/utils/profiling.py
- gpustack/worker/backends/base.py
- gpustack/worker/downloaders.py
- gpustack/worker/model_file_manager.py
- gpustack/worker/serve_manager.py
- gpustack/worker/worker.py
- tests/utils/test_hub.py
https://github.com/gpustack/gpustack/issues/1127
> feat: model file management

- docs/cli-reference/start.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/1206
> feat: Add an option to use hf_transfer for HF Hub downloads

- gpustack/worker/worker_manager.py
https://github.com/gpustack/gpustack/issues/1530
> feat: add worker name label

- gpustack/worker/model_file_manager.py
https://github.com/gpustack/gpustack/issues/1534
> fix: download task exception

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
- gpustack/routes/model_files.py
- gpustack/schemas/model_files.py
- gpustack/worker/downloaders.py
- gpustack/worker/model_file_manager.py
https://github.com/gpustack/gpustack/issues/1529
> feat: cleanup option on model file deletion

- gpustack/server/controllers.py
- gpustack/worker/model_file_manager.py
https://github.com/gpustack/gpustack/issues/1536
> fix: avoid repatching tqdm

- gpustack/api/middlewares.py
- gpustack/routes/rerank.py
- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/1317
Usage in vllm rerank response does not contain prompt_tokens.
> fix: vllm reranker usage

- gpustack/client/generated_http_client.py
- gpustack/codegen/templates/http_client.py.jinja
https://github.com/gpustack/gpustack/issues/1445
> fix: reverse local verify

- gpustack/mixins/active_record.py
- gpustack/server/controllers.py
https://github.com/gpustack/gpustack/issues/1543
> fix: match existing model files for local path models

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/1482
> fix: empty vram claim

- gpustack/utils/file.py
- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/1550
> feat: get sharded file paths for localpath files

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/policies/worker_filters/gpu_matching_filter.py
- gpustack/policies/worker_filters/label_matching_filter.py
- gpustack/routes/models.py
- gpustack/server/controllers.py
- tests/policies/candidate_selectors/gguf/test_gguf_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/1548
https://github.com/gpustack/gpustack/issues/1555
> refactor: move gpu filtering from worker filter to gguf resource selector

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/1560
> fix: compute allocatable vram

- gpustack/cmd/start.py
https://github.com/gpustack/gpustack/issues/1584
> fix: bool gpustack env

- gpustack/server/controllers.py
https://github.com/gpustack/gpustack/issues/1554
> fix: none file exception

- gpustack/ray/manager.py
https://github.com/gpustack/gpustack/issues/1567
> fix: restart ray on exit

- gpustack/server/controllers.py
https://github.com/gpustack/gpustack/issues/1543
> fix: resolved paths contains

- Dockerfile
- Dockerfile.cpu
- Dockerfile.dcu
- Dockerfile.musa
- Dockerfile.npu
- Dockerfile.rocm
- gpustack/utils/process.py
https://github.com/gpustack/gpustack/issues/1262
> refactor: add tini

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/routes/models.py
- tests/policies/candidate_selectors/vllm/test_vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/1562
> feat: validation for dist vllm limit per worker

- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/1553
Ref: https://py-filelock.readthedocs.io/en/latest/#filelock-vs-softfilelock
> fix: use soft filelock

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
> feat: add deepseek-v3-0324

- gpustack/migrations/utils.py
- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
https://github.com/gpustack/gpustack/issues/1603
> fix: migrate legacy hf cache

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- tests/policies/candidate_selectors/vllm/test_vllm_resource_fit_selector.py
- tests/utils/model.py
https://github.com/gpustack/gpustack/issues/1047
> fix: update non-LLM vllm claim

- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/1624
> chore: update exception message for empty architectures

- benchmarks/benchmark_llm.py
- gpustack/api/auth.py
- gpustack/api/middlewares.py
- gpustack/logging.py
- gpustack/routes/model_instances.py
- gpustack/routes/models.py
- gpustack/routes/openai.py
- gpustack/routes/workers.py
- gpustack/scheduler/scheduler.py
- gpustack/server/controllers.py
- gpustack/server/db.py
- gpustack/server/server.py
- gpustack/server/services.py
- gpustack/server/usage_buffer.py
- gpustack/server/worker_syncer.py
- poetry.lock
- pyproject.toml
- tests/utils/test_hub.py
https://github.com/gpustack/gpustack/issues/1256
> feat: add benchmark

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/schemas/models.py
https://github.com/gpustack/gpustack/issues/1665
https://github.com/gpustack/gpustack/issues/1652
> fix: dist vllm validation

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/1650
> fix: model env check

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
- gpustack/utils/file.py
- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/1603
> fix: migrate modelscope locks

- gpustack/worker/tools_manager.py
- pyproject.toml
https://github.com/gpustack/gpustack/issues/1619
> fix: custom vllm

- .github/workflows/docker-ci.yaml
- Dockerfile.npu
- fix failed to retrieve docker cached layers
- do not mount private cache in NPU building
> ci: adjust docker build

- benchmarks/benchmark_llm.py
https://github.com/gpustack/gpustack/issues/1677
> chore: no retry in benchmark

- gpustack/server/services.py
https://github.com/gpustack/gpustack/issues/1669
> fix: cache unbound result

- gpustack/server/services.py
https://github.com/gpustack/gpustack/issues/1669
> fix: expunge before cache

- gpustack/scheduler/evaluator.py
https://github.com/gpustack/gpustack/issues/1635
> fix: apply model validation to evaluate process

- Dockerfile.npu
- gpustack/schemas/models.py
- gpustack/worker/backends/ascend_mindie.py
> refactor: enhance mindie

- gpustack/scheduler/evaluator.py
https://github.com/gpustack/gpustack/issues/1664
> fix: gather evaluate task

- gpustack/utils/hub.py
https://github.com/gpustack/gpustack/issues/1659
> chore: ignore more patterns on modelscope config

- .github/workflows/docker-ci.yaml
- Dockerfile
- gpustack/utils/platform.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1382
> feat: support more cuda versions for llama-box

- gpustack/utils/hub.py
https://github.com/gpustack/gpustack/issues/1704
> fix: match hf posix paths

- gpustack/routes/rerank.py
- gpustack/routes/voice.py
https://github.com/gpustack/gpustack/issues/1710
> fix: rerank proxy

- .github/workflows/docker-ci.yaml
- Dockerfile.npu
- gpustack/utils/envs.py
- gpustack/worker/backends/ascend_mindie.py
- gpustack/worker/backends/base.py
- gpustack/worker/tools_manager.py
- adjust mindie dockerfile
- support multiple versions
- allow to control higher versions, like 2.0.T3
> fix: mindie versioned installation

- gpustack/worker/backends/ascend_mindie.py
> refactor(mindie): expose --max-link-num

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
- gpustack/worker/downloaders.py
Refer to issue: https://github.com/gpustack/gpustack/issues/1693
> fix: recreate users table with id autoincrement

- gpustack/scheduler/evaluator.py
https://github.com/gpustack/gpustack/issues/1721
> feat: validate tts on windows

- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/1736
> fix: sharded file size

- gpustack/policies/base.py
- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/policies/worker_filters/gpu_matching_filter.py
- gpustack/scheduler/evaluator.py
- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/1047
https://github.com/gpustack/gpustack/issues/1707
> feat: support overcommitment on manual scheudling

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
https://github.com/gpustack/gpustack/issues/1603
> fix: migrate hf cache withour symlink

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/1707
> fix: update message for manually selected gpus

- gpustack/scheduler/evaluator.py
https://github.com/gpustack/gpustack/issues/1746
> feat: add mindIE check

- .github/workflows/docker-ci.yaml
https://github.com/gpustack/gpustack/issues/1731
> ci: rc docker tags

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
https://github.com/gpustack/gpustack/issues/1603
> fix: move legacy hf cache

- gpustack/utils/hub.py
https://github.com/gpustack/gpustack/issues/1659
> fix: modelscope autoconfig allow list

- .github/workflows/docker-ci.yaml
https://github.com/gpustack/gpustack/issues/1761
> ci: add cpu docker images

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/1746
> feat: adapt with npu memory fraction parameter

- gpustack/utils/platform.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1755
> fix: get cuda version

- gpustack/routes/models.py
https://github.com/gpustack/gpustack/issues/1778
> feat: check backend device matching

- gpustack/scheduler/calculator.py
- gpustack/scheduler/evaluator.py
- gpustack/scheduler/scheduler.py
- gpustack/schemas/model_evaluations.py
https://github.com/gpustack/gpustack/issues/1643
> refactor: expose evaluation error

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
> feat: add gemma3 and llama4

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
> feat: add internvl3 and mistral small 3.1

- gpustack/scheduler/evaluator.py
- gpustack/utils/hub.py
https://github.com/gpustack/gpustack/issues/1706
> feat: add hub model auth check

- gpustack/worker/model_file_manager.py
https://github.com/gpustack/gpustack/issues/1638
> fix: download cancel

- tests/conftest.py
- tests/utils/test_command.py
> feat: unit tests for command.py

- Dockerfile.dcu
https://github.com/gpustack/gpustack/issues/1802
> fix: incorrect tool download

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
> add new model phi4-mini

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
- gpustack/schemas/model_files.py
- gpustack/server/controllers.py
- gpustack/server/services.py
https://github.com/gpustack/gpustack/issues/1817
> fix: big int file size

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
https://github.com/gpustack/gpustack/issues/1819
> fix: duplicate source enum on pgsql migration

- gpustack/ray/manager.py
https://github.com/gpustack/gpustack/issues/1825
> fix: no ray address for head

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1828
> fix: rpc-server link on load

- gpustack/config/config.py
https://github.com/gpustack/gpustack/issues/1825
> fix: init dirs

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1828
> fix: rm broken rpcserver link

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
> feat: add granite3.3

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1646
> chore: bump dependency

- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
https://github.com/gpustack/gpustack/issues/1856
> fix: remove legacy ollama model lock files

- gpustack/routes/dashboard.py
https://github.com/gpustack/gpustack/issues/1861
> fix: longer time range for dashboard usage

- docs/user-guide/inference-backends.md
@linyinli  will take over the **Parameters Reference** section later.
> docs: mindie backend introduction

- gpustack/mixins/active_record.py
- gpustack/routes/model_files.py
https://github.com/gpustack/gpustack/issues/1875
> fix: search model file by resolved paths

- gpustack/scheduler/evaluator.py
https://github.com/gpustack/gpustack/issues/1879
> feat: add vllm check with npus

- docs/user-guide/inference-backends.md
- gpustack/worker/backends/ascend_mindie.py
- gpustack/worker/backends/base.py
https://github.com/gpustack/gpustack/issues/1864
map the original model path, and change `config.json` and `generation_config.json`.
> feat(mindie): support fine-grained model configuration 

- docs/architecture.md
- docs/cli-reference/start.md
- gpustack/config/config.py
- gpustack/migrations/versions/2024_09_11_1629-6dcb3a50da19_update_model_instance_and_system_load_for_.py
- gpustack/migrations/versions/2024_12_26_1409-e6bf9e067296_add_model_categories.py
- gpustack/migrations/versions/2025_02_19_1743-c45e397531d1_add_env.py
- gpustack/routes/dashboard.py
- gpustack/routes/models.py
- gpustack/routes/openai.py
- gpustack/schemas/stmt.py
- gpustack/server/db.py
- gpustack/server/server.py
- poetry.lock
- pyproject.toml
> feat: support MySQL as external database

- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/1895
> fix: skip arch check on custom backend version

- .github/workflows/docker-ci.yaml
https://github.com/gpustack/gpustack/issues/1921
> ci: add cuda arm docker image

- gpustack/scheduler/scheduler.py
https://github.com/gpustack/gpustack/issues/1895
> fix: default to llm for unknown model

- gpustack/config/config.py
https://github.com/gpustack/gpustack/issues/1898
> fix: enable ray on cpu only node

- gpustack/worker/collector.py
- gpustack/worker/worker.py
- gpustack/worker/worker_manager.py
Refer to issue https://github.com/gpustack/gpustack/issues/1912
- Put `register_with_server` function into `_get_current_worker_id` to avoid worker id not found problem.
- Reports system info only when registering worker to avoid registration process costing too much time.
- The worker's initialized state will be `Not_Ready` to avoid model instance scheduled to newly created worker.
> fix: worker id not found when initializing worker takes too long

- gpustack/server/controllers.py
https://github.com/gpustack/gpustack/issues/1893
> fix: get model meta via worker proxy

- gpustack/routes/models.py
https://github.com/gpustack/gpustack/issues/1945
> chore: add docs link to enable ray message

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
- gpustack/worker/backends/llama_box.py
https://github.com/gpustack/gpustack/issues/1939
https://github.com/gpustack/gpustack/issues/1905
https://github.com/gpustack/gpustack/issues/1911
> feat: add qwen2.5-vl & pixtral gguf models to catalog

- gpustack/routes/model_instances.py
https://github.com/gpustack/gpustack/issues/1931
> fix: non-stream logs

- gpustack/utils/hub.py
Refer to https://github.com/gpustack/gpustack/issues/1937
> fix: add lock for downloading model pretrained config

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
https://github.com/gpustack/gpustack/issues/1939
> fix: update catalog

- gpustack/scheduler/evaluator.py
- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/1958
> feat: add limiter to model evaluation

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/1987
> chore: show versioned vllm installation logs

- gpustack/scheduler/evaluator.py
https://github.com/gpustack/gpustack/issues/1939
> feat: include env in default spec

- docs/faq.md
- docs/installation/amd-rocm/online-installation.md
- docs/installation/ascend-cann/online-installation.md
- docs/installation/hygon-dtk/online-installation.md
- docs/installation/installation-requirements.md
- docs/installation/moorethreads-musa/online-installation.md
- docs/installation/nvidia-cuda/online-installation.md
- docs/user-guide/inference-backends.md
https://github.com/gpustack/gpustack/issues/1982
> docs: clarify host network for dist vllm

- gpustack/worker/backends/base.py
- gpustack/worker/tools_manager.py
Refer to issue: https://github.com/gpustack/gpustack/issues/2014
> fix: should avoid using absolve path of data_dir

- docs/user-guide/inference-backends.md
https://github.com/gpustack/gpustack/issues/2019
> docs: add custom version for distributed vLLM notes

- gpustack/detectors/rocm_smi/rocm_smi.py
https://github.com/gpustack/gpustack/issues/2032
> fix: adapt with HCU rocm output

- gpustack/assets/model-catalog.yaml
- gpustack/routes/openai.py
https://github.com/gpustack/gpustack/issues/1939
https://github.com/gpustack/gpustack/issues/2036
> fix: huggingface dia catalog

- gpustack/routes/worker/proxy.py
https://github.com/gpustack/gpustack/issues/2036
> fix: update worker proxy timeout

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/2028
https://github.com/gpustack/gpustack/issues/2041
> fix: requests exceptions in tools manager

- gpustack/worker/tools_manager.py
address https://github.com/gpustack/gpustack/issues/2074
> chore(tool): bump version

- gpustack/utils/system_check.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/2081
> feat: add glibc check

- .github/workflows/docker-ci.yaml
- Dockerfile
Since v0.0.145, llama-box no longer supports CUDA 11.8
> ci: drop cuda11.8

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
https://github.com/gpustack/gpustack/issues/2123
> feat: add r1 0528 to catalog

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
https://github.com/gpustack/gpustack/issues/2146
> fix: remove incompatible Qwen3 config for vLLM Ascend

- gpustack/utils/platform.py
- gpustack/worker/backends/llama_box.py
- gpustack/worker/tools_manager.py
Refer to https://github.com/gpustack/gpustack/issues/2145
Try to use `llama-box-<os>-<arch>-<device>` first and fallback to `llama-box`
> feat: support using full path of llama-box

- benchmarks/benchmark_serving.py
- gpustack/api/middlewares.py
- gpustack/routes/openai.py
- gpustack/routes/proxy.py
- gpustack/security.py
- poetry.lock
- pyproject.toml
https://github.com/gpustack/gpustack/issues/1842
1. cache token hashing verification.
3. Replace httpx with aiohttp in proxy. [Reference](https://github.com/openai/openai-python/issues/1596)
Benchmark comparison:
`RTX 4080, Qwen2.5-0.5B, concurrency 256, max-tokens 128`
| Direct vLLM           | Optimized Proxy   | Before Optimization |
| ---------------- | ------ | -------------- |
| 4766.21 tok/s         | 4666.78 tok/s (-2%)   | 1653.21 tok/s  (-65%)    |
More details:
```
{
"model": "qwen2.5",
"total_requests": 768,
"successful_requests": 768,
"success_rate": 1.0,
"concurrency": 256,
"request_timeout": 300,
"max_completion_tokens": 128,
"total_time": 19.87,
"requests_per_second": 38.64,
"total_tokens": 94724,
"latency": {
"average": 5.87,
"p50": 5.57,
"p95": 8.54,
"p99": 11.03
}, …
```
> refactor: proxy performance tuning

- Dockerfile.npu
address https://github.com/gpustack/gpustack/issues/2180
> refactor: mindie turbo support

- gpustack/detectors/regredit/regredit.py
Filter out those inactivate GPU drivers
Refer to issue: https://github.com/gpustack/gpustack/issues/2166
> fix: multiple AMD GPU are detected when multiple driver installed

- .dockerignore
- .gitignore
- Dockerfile.npu
- gpustack/worker/tools_manager.py
- install GCC if less then Ubuntu 21.04
- link llama-box-rpc-server via directory relative linking
- build Python instead of install
- install MindIE via pipx venv
- use multi-stage build to install vLLM in parallel
- remove instance running envs of vLLM
> refactor(npu): tidy up mindie and vllm

- gpustack/scheduler/calculator.py
- gpustack/worker/backends/ascend_mindie.py
https://github.com/gpustack/gpustack/issues/2183
> fix: disallow abbrev parsing backend parameters

- gpustack/worker/tools_manager.py
address https://github.com/gpustack/gpustack/issues/2199
> refactor(mindie): idempotent multi-version installation

- gpustack/worker/rpc_server.py
- gpustack/worker/worker_manager.py
address https://github.com/gpustack/gpustack/issues/2094
> refactor: Enable rpc server cache by default

- gpustack/worker/tools_manager.py
Refer to https://github.com/gpustack/gpustack-helper/issues/14
Need to check link for downloaded binary and create link if needed.
> fix: the llama-box-rpc-server brokes with pre-downloaded llama-box

- gpustack/routes/models.py
address: https://github.com/gpustack/gpustack/issues/2154
> refactor:backend-parameters does not support --port

- gpustack/scheduler/scheduler.py
issue address: https://github.com/gpustack/gpustack/issues/1243
- Add existence checks for model instances when scheduling
> fix: resolve intermittent error logs during rapid batch model srart/stop operations

- gpustack/worker/tools_manager.py
address: https://github.com/gpustack/gpustack/issues/2241
also adjust DTK platform name getting.
> chore(llama-box): bump version

- docs/installation/cambricon-mlu/online-installation.md
- gpustack/config/config.py
- gpustack/detectors/cnmon/cnmon.py
- gpustack/detectors/detector_factory.py
- gpustack/schemas/workers.py
- gpustack/utils/platform.py
- gpustack/worker/backends/base.py
> Add Cambricon MLU

- gpustack/utils/hub.py
- gpustack/worker/downloaders.py
https://github.com/gpustack/gpustack/issues/2189
> fix: fix size computation for models with mmproj files

- gpustack/utils/hub.py
https://github.com/gpustack/gpustack/issues/2189
> fix: handle case for empty filename in size computation

- gpustack/utils/hub.py
- gpustack/worker/downloaders.py
- gpustack/worker/model_file_manager.py
https://github.com/gpustack/gpustack/issues/1592
> fix: delete mmproj temp files and already downloaded files

- gpustack/routes/openai.py
https://github.com/gpustack/gpustack/issues/2298
https://github.com/gpustack/gpustack/issues/2318
Problem:
1. `form_files` are not handled in streaming
2. Get `Chunk too big` errors for the last chunk of image streaming.
Solution:
1. Update form data parsing
2. Use sized iter_chunked.
> fix: handle form file and stream chunks

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/2346
> fix: allow custom vLLM on arm64 platform

- gpustack/api/middlewares.py
- gpustack/schemas/images.py
https://github.com/gpustack/gpustack/issues/1837
> fix: model usage for images

- gpustack/scheduler/evaluator.py
- gpustack/schemas/models.py
- gpustack/worker/backends/base.py
- gpustack/worker/backends/llama_box.py
https://github.com/gpustack/gpustack/issues/2326
> fix: empty params evaluation matches catalog specs

- gpustack/_sitecustomize.py
https://github.com/gpustack/gpustack/issues/2077
Problem:
PG may not be ready and bootstrap terminates by vllm check.
Solution:
Proceed until PG is ready.
> fix: add ray pg readiness check

- gpustack/worker/backends/llama_box.py
- gpustack/worker/rpc_server.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
- gpustack/worker/worker_manager.py
issuecomment address: https://github.com/gpustack/gpustack/issues/2322#issuecomment-3021361270
now,environment variable `GPUSTACK_DISABLE_DYNAMIC_LINK_LLAMA_BOX` also apply to default llama-box version
> feat: environment variable `GPUSTACK_DISABLE_DYNAMIC_LINK_LLAMA_BOX` apply to default llama-box version

- gpustack/detectors/npu_smi/npu_smi.py
address https://github.com/gpustack/gpustack/issues/2353
> refactor(npu-smi): pring warning in trace

- gpustack/worker/model_file_manager.py
fixed: https://github.com/gpustack/gpustack/issues/1592#issuecomment-3018260044
After completing the modifications related to resolved_paths, it can be used to accurately obtain the names of files to be deleted, and files that cannot be matched using the '*' wildcard can also be deleted now.
> fix: improve path handling for incomplete model file deletions

- gpustack/worker/tools_manager.py
address https://github.com/gpustack/gpustack/issues/2284
> chore(tool): bump llama-box version

- gpustack/routes/users.py
https://github.com/gpustack/gpustack/issues/2301
> fix: duplicate user message

- gpustack/routes/users.py
issue address:  https://github.com/gpustack/gpustack/issues/2192
> fix: password reset takes a while to take effect

- gpustack/worker/collector.py
issue address:  https://github.com/gpustack/gpustack/issues/2216
> fix: /v1/workers returns incorrect values for the "allocated" field

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/routes/models.py
- gpustack/worker/tools_manager.py
- pyproject.toml
https://github.com/gpustack/gpustack/issues/2236
> fix: reject distributed vllm with custom version

- gpustack/policies/base.py
- gpustack/policies/candidate_selectors/ascend_mindie_resource_fit_selector.py
- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
- gpustack/routes/dashboard.py
- gpustack/schemas/models.py
- gpustack/worker/collector.py
https://github.com/gpustack/gpustack/issues/2327
https://github.com/gpustack/gpustack/issues/303
> fix: missing resource allocation for subworkers

- gpustack/detectors/base.py
- gpustack/detectors/nvidia_smi/nvidia_smi.py
- gpustack/schemas/workers.py
- gpustack/utils/envs.py
- gpustack/worker/collector.py
- gpustack/worker/worker_manager.py
issue address: https://github.com/gpustack/gpustack/issues/2047
> fix: not providing sufficient information for Nvidia error

- gpustack/detectors/nvidia_smi/nvidia_smi.py
issue address: https://github.com/gpustack/gpustack/issues/2047
> chore: optimize error prompts when GPUDetectExepction

- gpustack/policies/candidate_selectors/ascend_mindie_resource_fit_selector.py
address https://github.com/gpustack/gpustack/issues/2459
> fix(selector/mindie): failed on evaluating mulitmodal models

- gpustack/worker/backends/base.py
- gpustack/worker/tools_manager.py
- gpustack/worker/worker.py
https://github.com/gpustack/gpustack/issues/2468
> refactor: install custom-version backends under data-dir

- gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
- gpustack/policies/utils.py
- tests/fixtures/estimates/deepseek_v3_0324_ud_iq1_s_disable_offload.json
- tests/fixtures/estimates/deepseek_v3_0324_ud_iq1_s_full_offload.json
- tests/fixtures/estimates/deepseek_v3_0324_ud_iq1_s_partial_offload.json
- tests/fixtures/estimates/fixtures.py
- tests/fixtures/workers/fixtures.py
- tests/fixtures/workers/macos_metal_3_m2ultra_192g.json
- tests/policies/candidate_selectors/gguf/test_gguf_resource_fit_selector.py
address https://github.com/gpustack/gpustack/issues/2451
this pr introduces two test cases to prevent usage validation bypassed with `-ngl=...`, https://github.com/gpustack/gpustack/issues/2451#issuecomment-3065673738.
> fix(selector/gguf): incorrect partial offloading in uma

- gpustack/assets/model-catalog-modelscope.yaml
https://github.com/gpustack/gpustack/issues/2487
> fix: incorrect file path for qwen3 embedding from modelscope

- gpustack/policies/candidate_selectors/ascend_mindie_resource_fit_selector.py
- gpustack/scheduler/scheduler.py
- gpustack/worker/backends/ascend_mindie.py
address https://github.com/gpustack/gpustack/issues/2497
- fix range check of --npu-memory-fraction
- fix typo when exception reports
- default --cpu-mem-size when it modified
- adjust parameters receiving logic
> refactor(mindie): validation

- gpustack/scheduler/calculator.py
- gpustack/utils/cache.py
- gpustack/utils/hub.py
issue address: https://github.com/gpustack/gpustack/issues/2119  
refactor:add GGUF repo cache 
path generation for cached GGUF files:  
config.cache_dir/repo-skeleton/URI-encode(f"{source}:{repo_id}")
Example output path:
cache_dir/repo-skeleton/huggingface%3Aunsloth%2FQwen3-0.6B-GGUF
> refactor:add GGUF repo cache

- gpustack/detectors/detector_factory.py
- gpustack/detectors/npu_smi/npu_smi.py
address https://github.com/gpustack/gpustack/issues/2509
give a debug log for skipping GPU device
> refactor(npu-smi): gather 310p chip

- gpustack/worker/tools_manager.py
issue address: https://github.com/gpustack/gpustack/issues/1734
> chore: update gguf-parse to v0.21.1

- gpustack/worker/backends/base.py
- gpustack/worker/backends/vllm.py
- gpustack/worker/rpc_server.py
address https://github.com/gpustack/gpustack/issues/2527
> fix(vllm/ascend): failed on running across multiple devices

- gpustack/api/middlewares.py
- gpustack/mixins/active_record.py
- gpustack/routes/api_keys.py
- gpustack/routes/gpu_devices.py
- gpustack/routes/model_files.py
- gpustack/routes/model_instances.py
- gpustack/routes/models.py
- gpustack/routes/openai.py
- gpustack/routes/users.py
- gpustack/routes/workers.py
- gpustack/server/db.py
- gpustack/server/deps.py
https://github.com/gpustack/gpustack/issues/1140
> feat: sqlite tuning

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
issue address: https://github.com/gpustack/gpustack/issues/2496
> fix: fail evaluation when single-node multi-GPU VRAM utilization

- Dockerfile.npu
- docs/cli-reference/start.md
- docs/installation/installation-requirements.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/ray/manager.py
try to address https://github.com/gpustack/gpustack/issues/2547, allow picking several nodes from the whole placement group of ray.
> fix(vllm/ascend/ray): failed on picking several nodes from the whole group

- Dockerfile
https://github.com/gpustack/gpustack/issues/2584
> revert: Force reinstall a standalone torch for vox-box in docker

- gpustack/policies/candidate_selectors/ascend_mindie_resource_fit_selector.py
address https://github.com/gpustack/gpustack/issues/2631
> fix(mindie): panic with quantization config

- gpustack/migrations/versions/2025_06_09_1507-cbbc03c88985_add_worker_uuid.py
https://github.com/gpustack/gpustack/issues/2635
> fix: none distributed servers on upgrade

- gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
https://github.com/gpustack/gpustack/issues/2646
Repair potential division-by-zero exceptions.
> fix: division-by-zero exceptions in auto-scheduling

- gpustack/routes/proxy.py
Refer to issue: https://github.com/gpustack/gpustack/issues/2677
> fix: skip headers in proxy response

- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/2634
> chore: bump llama-box to v0.0.169

- gpustack/worker/backend_dependency_manager.py
- gpustack/worker/backends/base.py
- gpustack/worker/tools_manager.py
https://github.com/gpustack/gpustack/issues/2665
Support custom dependency version control via the GPUSTACK_BACKEND_DEPS environment variable during deployment, while maintaining default dependencies for recent backend versions.
> feat: Optimize dependency management for specified backend versions

- gpustack/routes/model_instances.py
- gpustack/worker/model_file_manager.py
https://github.com/gpustack/gpustack/issues/2176
> fix: Update progress bar styling for frontend formatting compatibility.

- docs/cli-reference/start.md
https://github.com/gpustack/gpustack/issues/2719
> docs: update huggingface_token config example

- docs/overview.md
- docs/quickstart.md
> docs: add badges

- gpustack/scheduler/model_registry.py
address https://github.com/gpustack/gpustack/issues/2761
> refactor: support gpt-oss safetensor

- gpustack/assets/model-catalog-modelscope.yaml
- gpustack/assets/model-catalog.yaml
- Add GLM 4.5 FP8
- Add GLM 4.5 backend parameters
- Add GPT OSS vLLM backend
> chore: update catalog

- docs/user-guide/sso.md
- gpustack/cmd/start.py
- gpustack/config/config.py
- gpustack/routes/auth.py
issue address: https://github.com/gpustack/gpustack/issues/2740
add env:
GPUSTACK_SAML_SP_ATTRIBUTE_PREFIX : as attribute prefix.
> fix: fail load attributes when saml login

- gpustack/utils/hub.py
- tests/utils/test_hub.py
https://github.com/gpustack/gpustack/issues/2699
> feat: Add root directory filtering option for listing repository files

- gpustack/worker/exporter.py
**Issue:** #2811
**Problem:** 
Previously the metrics endpoint was mounted via `app.mount("/metrics", metrics_app)`, which caused FastAPI/Starlette to issue a 307 redirect from `/metrics` to `/metrics/`.
**Solution:**
This commit replaces the mount with a direct FastAPI route that uses `prometheus_client.generate_latest`, so that metrics are now available directly at `/metrics` without a trailing slash or redirect.
> fix: worker metrics endpoint only available at /metrics/ but not /metrics

- poetry.lock
- pyproject.toml
Fix CI: https://github.com/gpustack/gpustack/actions/runs/17900668510
> fix: add jinja2
