docs/installation/uninstallation.md
install.sh
install.sh.sha256sum

Fix the following issues:
- The /var/lib/gpustack directory requires sudo permissions to be removed.
- The /var/log/gpustack.log file is not removed.
- The uninstall script exits if a command encounters an error.

fix: uninstall permissions and ignore errors

---

gpustack/worker/serve_manager.py
gpustack/worker/worker.py

Problem:
Previously, serve-manager matches worker by hostname and may miss the worker with updated name.
https://github.com/gpustack/gpustack/issues/191

fix: match worker by name in serve manager

---

gpustack/worker/downloaders.py
gpustack/worker/inference_server.py

1. Progress is inconsistent on download resumption.
2. Outdated function paramters for download_blob retries.
https://github.com/gpustack/gpustack/issues/235
https://github.com/gpustack/gpustack/issues/250

fix download issues

---

gpustack/chat/manager.py

https://github.com/gpustack/gpustack/issues/276
model_validator should return self.(https://docs.pydantic.dev/latest/concepts/validators/#model-validators)
It prints warning in py3.12

chore: validator return self

---

gpustack/worker/backends/vllm.py

https://github.com/gpustack/gpustack/issues/313

fix: remove default model len for vllm backend

---

gpustack/api/responses.py
gpustack/routes/openai.py

Address https://github.com/gpustack/gpustack/issues/315
Fastapi/starlette StreamingResponse sets status_code on initialization. Use a wraper to handle it properly.
More context: https://github.com/fastapi/fastapi/discussions/10138

fix: handle error in openai proxy

---

gpustack/worker/backends/vllm.py

https://github.com/gpustack/gpustack/issues/345
As in https://github.com/vllm-project/vllm/blob/v0.6.2/vllm/config.py#L1743-L1751
Remove the assertion, it causes an opaque error if happen.

fix: detect mrope

---

gpustack/routes/rerank.py

https://github.com/gpustack/gpustack/issues/214#issuecomment-2409896557
top_n is optional per https://api.jina.ai/redoc#tag/rerank/operation/rank_v1_rerank_post

fix: optional top_n in rerank

---

gpustack/scheduler/scheduler.py

https://github.com/gpustack/gpustack/issues/452

fix: ignore exception when evaluating pretrained config fails

---

.github/workflows/ci.yml
hack/publish-pypi.sh
hack/windows/publish-pypi.ps1

We've refactored to reduce the package size to twenty-ish. Now it should be safe to publish rcs to pypi.
Remove workarounds to address publish issues. We can verify ci on publishing RCs in future releases.

ci: publish rcs

---

gpustack/server/server.py

When server exit before embedded worker is alive, the clean up results in 
```
self._popen.terminate()
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'terminate'
```
Also do join to avoid orphan process.

fix: improve exit error message

---

gpustack/worker/logs.py
tests/worker/test_logs.py

https://github.com/gpustack/gpustack/issues/483
Address an API issue when tail is larger than the number of total lines it returns repeated logs

fix: repeated logs on large tail

---

docs/installation/air-gapped-installation.md

#722 
Remove only-binary limit since some packages just provide source packages.
Examples:
https://pypi.org/project/aliyun-python-sdk-core/#files
https://pypi.org/project/antlr3-python-runtime/3.4/#files
Others:
crcmod-1.7.tar.gz
jaconv-0.4.0.tar.gz
jieba-0.42.1.tar.gz
openai-whisper-20240930.tar.gz
oss2-2.19.1.tar.gz

fix: remove only binary limit since some packages only provide source packages

---

gpustack/mixins/active_record.py
gpustack/routes/models.py
gpustack/routes/openai.py

https://github.com/gpustack/gpustack/issues/598
List of non-category models are availble with query `categories=`.

feat: support querying non-category models

---

gpustack/routes/model_instances.py
gpustack/server/app.py
gpustack/utils/file.py
gpustack/worker/logs.py
gpustack/worker/worker.py
poetry.lock
pyproject.toml
tests/worker/test_logs.py

https://github.com/gpustack/gpustack/issues/249
Problem:
When client disconnects, fd still holds for following logs.
Solution:
Use async log generator.
Others:
1.  Replace httpx with aiohttp which handles client disconnection better.
2. Add retries to log file check. It takes a short time for initialization and it will return 404 when log file is not yet available.

fix: async log generator

---

gpustack/client/generated_model_client.py
gpustack/client/generated_model_instance_client.py
gpustack/client/generated_user_client.py
gpustack/client/generated_worker_client.py
gpustack/codegen/templates/client.py.jinja
gpustack/mixins/active_record.py
gpustack/schemas/workers.py
gpustack/server/bus.py
gpustack/server/controllers.py
gpustack/server/worker_syncer.py

https://github.com/gpustack/gpustack/issues/268
https://github.com/gpustack/gpustack/issues/871
Problem:
The client does not detect connection interruption during system sleep and the watch request hangs.
Solution:
Add stream heartbeats and client timeout
Also, reduce the worker sync interval to make it more responsive.

fix: add watch timeout

---

.github/workflows/docker-ci.yaml

https://github.com/gpustack/gpustack/issues/991
Problem:
Previously, non-CUDA images are published to `latest`. [PR 762](https://github.com/gpustack/gpustack/pull/762) tends to resolve it but resulting in `latest-<device>` tags missing.
Solution:
Set `latest=false` in docker metadata flavor. It controls auto-generated latest tag.
Ref:
https://github.com/docker/metadata-action?tab=readme-ov-file#flavor-input
Test Result:
https://github.com/gitlawr/test/actions/runs/12801567432/job/35691246938

ci: update docker tag latest flavor

---

gpustack/routes/dashboard.py

https://github.com/gpustack/gpustack/issues/1062
Happends when using pg and token count query result is null

fix: dashboard token ordering

---

gpustack/schemas/users.py

Currently password's special character list has two version: `[!@#$%^&*(),.?":{}|<>]` and `[!@#$%^&*_+]`. 
It should be consistent.
* `[!@#$%^&*(),.?":{}|<>]`
- https://github.com/gpustack/gpustack/blob/v0.5.1/gpustack/schemas/users.py#L29
- https://github.com/gpustack/gpustack/blob/v0.5.1/gpustack/schemas/users.py#L50
* `[!@#$%^&*_+]`
- https://github.com/gpustack/gpustack/blob/v0.5.1/gpustack/security.py#L29
- https://github.com/gpustack/gpustack-ui/blob/0.3.2/src/config/index.ts#L51

Make password's special character list consistent

---

install.sh
install.sh.sha256sum

address https://github.com/gpustack/gpustack/issues/1207
When user site is disabled, `python3 -m site --user-base` exits with none-zero code and halts the installation script.
Ref: https://github.com/python/cpython/blob/9e23e0ad2cc4267829388bc29688ac0c2bfb3604/Lib/site.py#L720-L725

fix: no termination on disabled user site

---

Makefile

https://github.com/gpustack/gpustack/issues/1287
Problem:
Running make on windows may result in error due to execution policy. The make targets include error messages and available script list, making the error opaque.
Under the hood:
```
. : File C:\Users\alice\Documents\WindowsPowerShell\profile.ps1 cannot be loaded because running scripts is disabled on this system.
For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
```

fix: skip profile and execution policy on powershell make

---

gpustack/worker/backends/vox_box.py

https://github.com/gpustack/gpustack/issues/1338
We probably need static checks like mypy to mitigate this.

fix: mismatch parameters for get_inference_running_env

---

gpustack/worker/worker.py

https://github.com/gpustack/gpustack/issues/1300
Ensure the system username is ASCII-decoded to maintain compatibility.
Context: https://github.com/fastapi/fastapi/blob/b0215699137c41a96c57f650640cb9db1c25314a/fastapi/security/http.py#L211

fix: avoid worker name in user name

---

gpustack/scheduler/calculator.py
gpustack/worker/serve_manager.py
gpustack/worker/tools_manager.py

- Issue: #1240 
- Problem: image models just have one item in parser's result, so log item[1] will cause out of index
```json
{
"estimate": {
"items": [
{
"fullOffloaded": true,
"ram": {
"remote": false,
"position": 0,
"uma": 349696800,
"nonuma": 506983200
},
"vrams": [
{
"remote": false,
"position": 0,
"uma": 9019848372,
"nonuma": 13216492079
}
]
}
],
"type": "model",
"architecture": "stable_diffusion_3_x",
"flashAttention": false,
"noMMap": true,
"imageOnly": true,
"distributable": true
}
}
```

fix: log partial offload info for image model cause stuck in analyzing

---

gpustack/worker/collector.py

#1258
Allows users to define the gpu and system info separately or both.

refactor: support for defining gpu and system info separately

---

docs/installation/docker-installation.md

Based on feedback, when installing GPUStack using Docker on NVIDIA, disabling systemd cgroup management is required. Otherwise, users will encounter the error: `Failed to initialize NVML: Unknown Error`
Add guidance for this in the Docker Installation docs.

docs: add instructions for disabling systemd cgroup management

---

gpustack/utils/hub.py
gpustack/worker/backends/base.py
gpustack/worker/backends/vllm.py
tests/pretrained_config/test_pretrained_config.py

https://github.com/gpustack/gpustack/issues/1408
https://github.com/gpustack/gpustack/issues/1342
1.  Fix None global config as it's not initialized in serving process.
2. Support getting context size from text_config.
3. Update new keys acccording to current vLLM implementation.

fix: infer max model len

---

gpustack/logging.py

Supress repeated logs like the following
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
```

chore: Suppress warnings from transformers

---

gpustack/worker/serve_manager.py

https://github.com/gpustack/gpustack/issues/1215
We've gathered async tasks to detect coroutine exceptions. The missing part is that it may enter infinity loop in watch_model_instances when registration fails. Raise the error in this case so that external manager like systemd/container runtime can restart the failed worker.

fix: skip watch loop if fail to get worker

---

gpustack/routes/model_instances.py

When worker is installed using custom worker port other than 10150, by using '--worker-port' worker options, GpuStack can not fetch log from worker. And it will throw following error on gpustack serevr:
```text
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
result = await app(  # type: ignore[func-returns-value]
File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
await super().__call__(scope, receive, send)
File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 112, in __call__ …
```

Fix error "Error fetching serving logs" when worker is installed using custom worker port other than 10150

---

docs/cli-reference/start.md
gpustack/cmd/start.py
gpustack/config/config.py
gpustack/server/server.py

https://github.com/gpustack/gpustack/issues/1271
Start with default parameters when no parameters are specified:
When more precise control is required, modify the configuration file as shown in the figure below, ensuring that the parameters comply with the specifications of FastAPI's CORSMiddleware.
https://fastapi.tiangolo.com/tutorial/cors/#use-corsmiddleware

fix: Allow users to customize CORS-related parameters.

---

gpustack/assets/model-catalog-modelscope.yaml
gpustack/assets/model-catalog.yaml

The `bge-large-en-v1.5` and `bge-large-zh-v1.5` models have a maximum context length of only 512 tokens.

fix: wrong context length

---

gpustack/worker/rpc_server.py
gpustack/worker/tools_manager.py

Mac / Linux: use symlink for rpc server
windows: copy llama-box to a new file

fix: avoid rpc server and inference server use same name

---

gpustack/utils/process.py

In the terminate_process method, adding wait after a failed kill operation helps reclaim the child process and prevents the creation of zombie processes

fix: zombie processes being generated when stopping models inside containers.

---

gpustack/cmd/start.py

Fix the error
```
2025-03-25T17:27:21+08:00 - gpustack.cmd.start - CRITICAL - 'Config' object has no attribute 'get'
```

fix: get config attr

---

Dockerfile.dcu

This PR addresses a kernel crash that occurs under high concurrency when using AWQ INT4 quantized models, particularly on systems running a CK-patched kernel.
Upgraded `lmslim` from version `0.1.2` to `0.2.1`, which resolves the issue based on internal testing.
Fixes https://github.com/gpustack/gpustack/issues/1726
- Kernel: CK-patched Linux (6.x)
- Quantization: AWQ INT4
- Concurrency: High-load, multi-request scenario

fix(dcu): crash with AWQ INT4 under high concurrency

---

gpustack/routes/users.py
gpustack/server/services.py

Refer to https://github.com/gpustack/gpustack/issues/1693#issuecomment-2803591202
The locked_cached decoder has been changed to operating single cache. As the origin cached class creates one cache instance per decorated function and it can't access from outside.

fix: Delete api_keys cache when deleting user

---

gpustack/scheduler/calculator.py
gpustack/worker/backends/llama_box.py

see below investigation comments:
- darwin-metal https://github.com/gpustack/gpustack/issues/1646#issuecomment-2801360533
- linux-musa https://github.com/gpustack/llama-box/issues/46#issuecomment-2804339612
if you get stuck in model loading with mmap in some backends, like
Ascend CANN, you can try with `--no-mmap`.
with mmap, page fault interruption is the killer, you can enable mlock
with `--mlock`. for scenarios with limited memory, `--mlock` doesn't
apply.

fix(llama-box): failed to load model

---

Dockerfile.dcu
Dockerfile.dcu.base
Dockerfile.rocm

1. Optimized the image to reduce unnecessary size: 35.7GB → 31.2GB
2. Starting from APT 1.1 (currently 2.4.13), apt-get clean is performed automatically.
3. Add `/root/.local/bin` to PATH globally.
4. Add ip and ping commands.
5. Some unnecessary characters.

chore(dcu): optimize Dockerfile to reduce image size

---

Dockerfile.npu

- bump python 3.11
- split into multiple stages for reusing,
for example, you can use `docker build --tag=gpustack/gpustack:npu-base --file=Dockerfile.npu --target base --progress=plain .` to prepare the npu-base.
- fix https://github.com/gpustack/gpustack/issues/1779

refactor(mindie): optimize docker build

---

gpustack/worker/backends/ascend_mindie.py

- fix failed on default launch
- fix failed on exposing metrics, https://github.com/gpustack/gpustack/issues/1785
- align default context length to 8192, https://github.com/gpustack/gpustack/issues/1805

fix(mindie): failed on default launch

---

gpustack/scheduler/calculator.py
gpustack/worker/backends/llama_box.py

- revert the change introduced by https://github.com/gpustack/gpustack/pull/1767.
- enable calculator to recognize `--mmap` option.

refactor(calculator): gguf-parser receive parameters 

---

Dockerfile.npu

- there is no [mindie] optional dependency, let's remove it.
- install vox_box option, although it's useless in Ascend hardware, it's important to align with other backend packing.
- install pipx, an optional virtual env management rather than venv.
cc @linyinli

ci(mindie): adjust gpustack install

---

gpustack/server/app.py
gpustack/server/server.py

In PR #1890, I initially attempted to retrieve the config using cfg = get_global_config() directly at the module level in gpustack/server/app.py. However, due to the timing of FastAPI app instantiation and module loading, this approach is not reliable — the config may not be available yet at import time, and setting app.state.server_config later does not affect previously evaluated module-level code.
I sincerely apologize for the oversight.
After reviewing the issue more carefully, I explored a new approach: using a `ContextVar` to store the Config object in the context.This allows FastAPI and its routes to dynamically read the correct configuration value even after the app has been initialized.
I also evaluated an alternative method: hiding documentation routes manually in the lifespan …

fix(config): propagate global Config into asyncio context

---

gpustack/worker/backends/vox_box.py

https://github.com/gpustack/gpustack/issues/1943
vox-box accepts device index via arguments. Passing the index via device env may cause conflicts.

fix: do not pass vendor specific device env to vox-box

---

poetry.lock
pyproject.toml

To avoid using NullPool as default pool while running create_engine() in aiosqlite.
Refer to issue: https://github.com/gpustack/gpustack/issues/1892
**After updated the pyproject.toml and run `poetry lock`, the changes of poetry.lock are huge. and I don't know it is by design ro not.**

deps: bump sqlalchemy to version newer 2.0.38

---

Dockerfile.npu
docs/user-guide/inference-backends.md
gpustack/worker/backends/ascend_mindie.py

- update dockerfile
+ bump CANN to 8.1.rc1.beta1
- adjust instance parameters
- compatible mindie 1.0.0 and 2.0.rc1
- revert the vox-box installation introduced by https://github.com/gpustack/gpustack/pull/1919
fix https://github.com/gpustack/gpustack/issues/1997

refactor(mindie): bump to 2.0.rc1

---

README.md
README_CN.md
README_JP.md

This PR adds Japanese translation for the README to improve accessibility for Japanese developers and the
Japanese-speaking community.
- Added `README_JP.md` with complete Japanese translation of the main README
- Updated language navigation links in all README files (`README.md`, `README_CN.md`, `README_JP.md`)
GPUStack is a powerful tool that could benefit many Japanese developers. Adding Japanese documentation will:
- Lower the language barrier for Japanese-speaking users
- Expand the project's reach in the Japanese developer community
- Contribute to the internationalization efforts of the project
- Maintained the same structure and formatting as the original English README
- Used appropriate technical terminology commonly used in Japanese developer communities
- Kept all code …

docs: add Japanese README translation

---

gpustack/routes/model_instances.py
gpustack/routes/worker/logs.py
gpustack/utils/file.py

https://github.com/gpustack/gpustack/issues/2157
Problem: Current retry period is short and the log file may not be ready when the model instance status turns to starting.
Solution: Increase retry and improve exception handling.

fix: exception on log file not ready

---

gpustack/scheduler/calculator.py
gpustack/worker/backends/ascend_mindie.py

https://github.com/gpustack/gpustack/issues/2183

[v0.6] fix: disallow abbrev parsing backend parameters

---

.dockerignore
.gitignore
Dockerfile.npu
docs/user-guide/inference-backends.md
gpustack/worker/backends/vllm.py
gpustack/worker/tools_manager.py
hack/build.sh
hack/install.sh

- bump mindie to 2.0.RC2
- build local python instead of install
- install mindie via pipx venv
- use multi-stage build to install vllm in parallel
- remove instance running envs of vllm
remove the default environment variable setting, which can be enabled during instance launch. cc @linyinli 
```
ARCH="$(uname -m)"
if [[ "$ARCH" == "aarch64" && "$CANN_CHIP" == "910b" ]]; then
EXPORT_PYTHON_LIB="export LD_LIBRARY_PATH=$(pipx environment --value PIPX_LOCAL_VENVS)/vllm-ascend/lib/python3.11/site-packages/torch/lib:\${LD_LIBRARY_PATH}"
echo "${EXPORT_PYTHON_LIB}" >> /etc/profile
echo "${EXPORT_PYTHON_LIB}" >> ~/.bashrc
echo 'export PYTORCH_NPU_ALLOC_CONF="expandable_segments:True"' >> /etc/profile
echo 'export PYTORCH_NPU_ALLOC_CONF="expandable_segments:True"' >> ~/.bashrc
echo 'export …
```

refactor(npu): tidy up mindie and vllm

---

gpustack/routes/dashboard.py
gpustack/schemas/common.py
gpustack/schemas/dashboard.py

https://github.com/gpustack/gpustack/issues/1837
Add `/v1/dashboard/usage/stats` API. Examples:
`/v1/dashboard/usage/stats?start_date=2025-06-20&end_date=2025-06-22&model_ids=1&model_ids=2&user_ids=1`
(Same structure as the model_usage in existing /v1/dashboard)
```
{
"api_request_history":
[
{
"timestamp": 1750348800,
"value": 1.0
},
{
"timestamp": 1750608000,
"value": 1.0
}
],
"completion_token_history":
[
{
"timestamp": 1750348800,
"value": 78.0
},
{
"timestamp": 1750608000,
"value": 69.0
}
],
"prompt_token_history":
[
{
"timestamp": 1750348800,
"value": 9.0
},
{
"timestamp": 1750608000,
"value": 9.0
}
]
}
```
`/v1/dashboard/usage?start_date=2025-06-20&end_date=2025-06-22&model_ids=1&model_ids=2&user_ids=1`
```
{
"items":
[
{
"user_id": 1,
"id": 1,
"request_count": 1,
"model_id": 1, …
```

feat: add usage query apis

---

gpustack/utils/platform.py
gpustack/worker/backends/llama_box.py
gpustack/worker/tools_manager.py

Revert some of the logic from 03cd217 as it has been implemented with bec76ba.
Multiple versions of llama-box support meet the needs of differentiating multiple devices.
Refer to 
- https://github.com/gpustack/gpustack/issues/2145

fix: simplify llama-box download logic

---

gpustack/cmd/start.py
gpustack/config/config.py
gpustack/utils/envs.py
gpustack/utils/platform.py
gpustack/worker/backends/llama_box.py
gpustack/worker/tools_manager.py

issues address: https://github.com/gpustack/gpustack/issues/2322, https://github.com/gpustack/gpustack/issues/2297
Introduce environment variable to toggle between static/dynamic linking in llama-box:
- Set `GPUSTACK_DISABLE_DYNAMIC_LINK_LLAMA_BOX=true` to disable dynamic linking
- Static libraries stored in {$data_dir}/bin/llama-box/static with versioned subdirs
- Default behavior remains dynamic linking when env var not set

feat(config): Add GPUSTACK_DISABLE_DYNAMIC_LINK_LLAMA_BOX env var for llama-box deployment control

---

gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
gpustack/scheduler/calculator.py
tests/fixtures/estimates/fixtures.py

Type hint in `architecture: Optional[architecture] = None` is considered to be the variable and breaks deserializing.

fix: capitalize dataclass

---

gpustack/policies/candidate_selectors/ascend_mindie_resource_fit_selector.py
gpustack/policies/candidate_selectors/gguf_resource_fit_selector.py
gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
tests/policies/candidate_selectors/ascend_mindie/test_ascend_mindie_resource_fit_selector.py
tests/policies/candidate_selectors/vllm/test_vllm_resource_fit_selector.py

1. Change `['ascend_0', 'ascend_1']...(more 2)` to `['ascend_0', 'ascend_1'...(more 2)]` in multi worker scenario, achieving better visual integration"
2. Correct the usage of singular and plural words in sentences.
3. Swap the order of RAM and VRAM in MindIE to align with llama-box.

fix: correct compatibility check messages

---

gpustack/policies/worker_filters/label_matching_filter.py

address typo found in https://github.com/gpustack/gpustack/issues/2474

chore(mindie): fix typo in lable matching filter

---

gpustack/assets/model-catalog-modelscope.yaml
gpustack/assets/model-catalog.yaml
gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
gpustack/routes/openai.py

https://github.com/gpustack/gpustack/issues/2462
Unlike other embedding/reranker models, current vLLM implementation allocates vram according to --gpu-memory-utilization for the Qwen3 Embedding series. Obey this behavior in GPUStack scheduling/evaluation.
https://github.com/gpustack/gpustack/issues/2244
Apply Qwen3 Reranker official template so that it works for clients out of the box.

fix: respect vram utilization for qwen3 embedding

---

Dockerfile.npu

This PR will update the vLLM and vLLM-Ascend versions of our NPU Docker image.
Although vLLM v0.9.2 depends on PyTorch 2.7.0, vLLM-Ascend v0.9.2rc1 depends on PyTorch 2.5.1, so this PR adjusts the installation sequence to `vLLM -> PyTorch(and its friends) -> vLLM-Ascend`.
With vLLM-Ascend v0.9.2rc1, we can deploy [Pangu Pro MoE](https://gitcode.com/ascend-tribe/pangu-pro-moe-model) now. For a better chat experience, users can change the `tokenizer_config.json` that belongs to the Pangu Pro MoE model as below:
1. Modify the token mapper, make `45974=<think>` and `45982=</think>`.
2. Modify the chat template, increase the official system prompt: `你必须严格遵守法律法规和社会道德规范。生成任何内容时，都应避免涉及暴力、色情、恐怖主义、种族歧视、性别歧视等不当内容。一旦检测到输入或输出有此类倾向，应拒绝回答并发出警告。例如，如果输入内容包含暴力威胁或色情描述，应返回错误信息：“您的输入包含不当内容，无法处理。”`.

chore(npu): bump vllm version

---

gpustack/policies/candidate_selectors/ascend_mindie_resource_fit_selector.py

address reopened https://github.com/gpustack/gpustack/issues/2459
- calculate head_dim if it is None
- distinguish a model to be MLA model by *_lora_rank

fix(selector/mindie): failed on recoginizing n_groups=1 mla model

---

Dockerfile

https://github.com/gpustack/gpustack/issues/2377
CosyVoice in vox-box requires transformer==4.51.3, while gpustack's dependencies already use transformer==4.53.1. The newer version causes abnormal audio output from CosyVoice. Isolate the environments to prevent future conflicts.

feat: Isolate virtual environments for vox-box and gpustack

---

poetry.lock
pyproject.toml

Relaxing transformers version restrictions which allows installer to build gpustack with transformers 4.51.3.
Refer to issue: https://github.com/gpustack/gpustack/issues/2377,
and PR https://github.com/gpustack/gpustack/pull/2473

deps: relaxing transformers version restrictions

---

docs/cli-reference/start.md

Describe the environment variable `GPUSTACK_DISABLE_DYNAMIC_LINK_LLAMA_BOX`.

chore: update start.md

---

gpustack/scheduler/calculator.py
gpustack/utils/cache.py
gpustack/utils/convert.py
gpustack/utils/hub.py
poetry.lock
pyproject.toml

issue address: https://github.com/gpustack/gpustack/issues/2519
The main adjustments are as follows: 
1. GGUF model can use --cache-expiration optio configure repo file cache expirationand
2. Manually determine whether the cache file of model_scope exists
3. Vox-box model Still cannot be deployed in an offline environment

fix: offline environment model deployment failed

---

Dockerfile.npu
docs/cli-reference/start.md
docs/installation/installation-requirements.md
gpustack/cmd/start.py
gpustack/config/config.py
gpustack/worker/backends/vllm.py

address https://github.com/gpustack/gpustack/issues/2547, a continuous work for https://github.com/gpustack/gpustack/pull/2560.
- correct sitecustomize location
- narrow worker range port to 40100-40999
- correct ray request unit resource key

fix(vllm/ascend/ray): failed on picking several nodes from the whole group 2

---

gpustack/scheduler/evaluator.py
gpustack/utils/cache.py
gpustack/utils/hub.py

issue address: https://github.com/gpustack/gpustack/issues/2565  
When evaluating a model in the catalog, an auth_check is performed,the operation can't run in air-gapped environments. This behavior has now been modified to first check the cache.

fix(catalog): evaluation model failure in air-gapped environment

---

Dockerfile

Avoid specifying triton 3.31 installation on arm64 platforms since no compatible version exists, aligning with pyproject.toml constraints.

fix: Specify the Triton version only for platform amd64

---

gpustack/policies/candidate_selectors/vllm_resource_fit_selector.py
gpustack/policies/utils.py
gpustack/scheduler/scheduler.py
tests/policies/candidate_selectors/vllm/test_vllm_resource_fit_selector.py

https://github.com/gpustack/gpustack/issues/2646#issuecomment-3149768495
- Repaired the issue where GPU allocations that don't meet VRAM requirements could still pass compatibility checks when a specific GPU count is specified.
- Add support for retrieving num_attention_heads from thinker_config.
- Improve the scheduling test case.

fix: Enhance attention heads validation

---

gpustack/routes/model_instances.py
gpustack/routes/worker/logs.py
gpustack/worker/model_file_manager.py

related issue: https://github.com/gpustack/gpustack/issues/2176
By redirecting model download logs to a separate log file and implementing status checks in the API, we can dynamically control whether the model instance logs include download progress.
As for the issue below, I haven't been able to successfully reproduce it yet, so I can't determine the cause at this stage.
https://github.com/gpustack/gpustack/issues/2176#issuecomment-3095570315

feat: Log the download progress in the model instance's log file.

---

pack/Dockerfile
pack/Dockerfile.cpu
pack/Dockerfile.npu

https://github.com/gpustack/gpustack/issues/2687#issue-3296979994
Seperate built-in venvs(`/opt/venvs/*`) and pipx venvs(`data-dir/pipx/venvs` created by custom version backend auto installtion). Set PIPX envs so that the command can be used properly.

fix: update pipx envs

---

gpustack/detectors/nvidia_smi/nvidia_smi.py

https://github.com/gpustack/gpustack/issues/2532
Parse MIG device memory information from nvidia-smi -q -x XML output, then construct GPU names using IDs and other metadata.
However, even with SYSTEM_ADMIN privileges granted to the container, physical GPU utilization metrics remain inaccessible, requiring temporary zero-value substitution.

feat: Add support for Nvidia MIG detection in containerized environments.

---

gpustack/schemas/users.py

Fix the issue when creating user
```
2 validation errors:\n  {'type': 'missing', 'loc': ('body', 'cluster_id'), 'msg': 'Field required', 'input': {'username': 'sdfs', 'full_name': 'sdfs', 'is_admin': False, 'password': 'Admin123!'}}\n  {'type': 'missing', 'loc': ('body', 'worker_id'), 'msg': 'Field required', 'input': {'username': 'sdfs', 'full_name': 'sdfs', 'is_admin': False, 'password': 'Admin123!'}}\n"
```

fix: set user's cluster_id/worker_id default to None

---

docs/stylesheets/extra.css

docs: hide MkDocs footer in generated pages
